# Generated by Django 6.1.1 on 2026-10-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelStation",
            fields=[
                ("opis_id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(max_length=2)),
                ("rack_id", models.PositiveIntegerField()),
                (
                    "price",
                    models.DecimalField(decimal_places=8, help_text="Retail price in USD per gallon.", max_digits=10),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "indexes": [models.Index(fields=["latitude", "longitude"], name="station_lat_lon_idx")],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(help_text="Normalized name, see gazetteer.normalize_place_name.", max_length=128),
                ),
                ("state", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=128)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("key", "state"), name="unique_place_key_state")],
            },
        ),
    ]
